#! /bin/bash

CLOCK_EMOJIS=🕐🕜🕑🕝🕒🕞🕓🕟🕔🕠🕕🕡🕖🕢🕗🕣🕘🕤🕙🕥🕚🕦🕛🕧🕐

function hour_part {
	MIN=$((10#$(date +%M)))

        if [ $MIN -ge 0 ] && [ $MIN -le 14 ]
        then
                echo 2
        elif [ $MIN -ge 15 ] && [ $MIN -le 44 ]
        then
                echo 1
        else
                echo 0
        fi
}

echo ${CLOCK_EMOJIS:$((2*10#$(date +%I)-$(hour_part))):1} > ~/.vars/clockemoji
